server: 
  port: 8761

#Spring Cloud Config配置信息
spring:
  application:
    name: pentaQEurekaServer
  cloud: 
    config: 
      uri: http://${configServer.ip}:${configServer.port}
      name: pentaQEurekaServer
      profile: ${app.profile:dev}

#Eureka 配置信息
eureka:
  instance:
    hostname: ${eureka.instance.hostname} #暴露的hostname
  client:
    registerWithEureka: ${eureka.client.registerWithEureka} #是否注册到eureka
    fetchRegistry: ${eureka.client.fetchRegistry} #是否从eureka获取注册信息
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #serviceUrl指向与本地实例相同的主机
      #defaultZone: http://user:password@localhost:8761/eureka #带有安全验证的服务中心
    healthcheck: 
      enabled: true #默认是true，Eureka的监控检查，这个配置需要配置在application中，配置bootstrap中可能会导致一系列的问题