server: 
  port: 8081

#Spring Cloud Config配置信息
spring:
  application:
    name: pentaQServer
  cloud: 
    config: 
      uri: ${configServer.url}
      name: pentaQServer
      profile: ${app.profile:dev}

#Eureka 配置信息
eureka: 
  client:
    serviceUrl: 
      defaultZone: ${eureka.defaultZone}
      
#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.99.100:3306/blog?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 123456

#mybatis config
mybatis:
  typeAliasesPackage: com.pentaQ.service.model
  mapperLocations: classpath:mapper/*.xml